stages:
  data-ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data-ingestion.test_size
    outs:
    - data/raw

  data-preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  feat-engg:
    cmd: python src/feat_engg.py
    deps:
    - data/processed
    - src/feat_engg.py
    params:
    - feat-engg.max_features 
    outs:
    - data/features
  model-building:
    cmd: python src/model_building.py
    deps:
    - data/features
    - src/model_building.py
    params:
    - model-building.n_estimators
    - model-building.learning_rate
    outs:
    - sentiment_model.joblib
  model-evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/features
    - sentiment_model.joblib
    - src/model_evaluation.py
    metrics:
    - metrics.json
